export const FETCH_LIST = '[questions]: FETCH_LIST'
export const FETCH_DETAIL = '[questions]: FETCH_DETAIL'
export const CREATE = '[questions]: CREATE'
export const UPDATE = '[questions]: UPDATE'
export const DELETE = '[questions]: DELETE'
